# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BlueTeeth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BlueTeethConnection(object):
    def setupUi(self, BlueTeethConnection):
        BlueTeethConnection.setObjectName("BlueTeethConnection")
        BlueTeethConnection.resize(400, 182)
        self.buttonBox = QtWidgets.QDialogButtonBox(BlueTeethConnection)
        self.buttonBox.setGeometry(QtCore.QRect(300, 50, 81, 191))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(BlueTeethConnection)
        self.label.setGeometry(QtCore.QRect(20, 60, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(BlueTeethConnection)
        self.buttonBox.accepted.connect(BlueTeethConnection.accept) # type: ignore
        self.buttonBox.rejected.connect(BlueTeethConnection.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BlueTeethConnection)

    def retranslateUi(self, BlueTeethConnection):
        _translate = QtCore.QCoreApplication.translate
        BlueTeethConnection.setWindowTitle(_translate("BlueTeethConnection", "Dialog"))
        self.label.setText(_translate("BlueTeethConnection", "Connections succeed！"))
